
= SourceBuddy






SourceBuddy is a very simple Java source compiler facade in front of the JDK-provided `javac` compiler.
I designed it for applications creating Java source code on the fly during run-time.
The JDK API is complex and hard to use.
You have to implement a `JavaFileManager` and `JavaFileObject`, which is possible, but SourceBuddy does it for you.

Using SourceBuddy, you do not need to implement anything except your application logic.
You get a `Compiler` object calling the `Compiler.java()`, and from there, all you need is

* specify the source code either as Java strings or files,
* call `compile()`
* fetch the compiled `.class` files or the loaded classes.

The library provides a one-call API if your application generates only one Java file.
You can call the `Compiler.compile(className,sourceCode)` static method that does everything.
It compiles the source code, loads the class(es) generated from the source, and returns the class.

The following example shows how to use the one-call API:

[source,java]
----
 1. String source = "package com.sb.demo;\n" +
 2.         "\n" +
 3.         "public class MyClass implements TestInterface{\n" +
 4.         "    public String a() {\n" +
 5.         "        return \"x\";\n" +
 6.         "  }\n" +
 7.         "}";
 8. Class<?> myClassClass = Compiler.compile("com.sb.demo.MyClass", source);
 9. TestInterface myClass = (TestInterface)myClassClass.getConstructor().newInstance();
10. String s = myClass.a();

----

The variable `source` defines the to-be-compiled code.
The compilation and loading of the class happen on line 8.
It is the line using the compilation API.
The `MyClass` implemented interface, `TestInterface`, is defined in the project's test.
Classes and interfaces in the host application executing the compilation are available for the Java code to be compiled.
The instance created using reflection can be cast to the implemented interface (line 9), and line 10 invokes the method defined there.

In this document, we will explain the details of how to use the library, including

* dependency parameters,

* simple API,

* Fluent API,

* support.

== Dependency Parameters


To use the library, it has to be on the classpath for your application, as it is for every library.
The library is available from Maven central.
The Maven central coordinates are:

[source,xml]
----
<dependency>
    <groupId>com.javax0.sourcebuddy</groupId>
    <artifactId>SourceBuddy</artifactId>
    <version>1.0.1-SNAPSHOT</version>
</dependency>
----

SourceBuddy requires Java 17.

== Simple API

You can use the simple API in projects requiring only one source file in a compilation unit.
To do that, the class `com.javax0.sourcebuddy.Compiler` defines a static method `compile`.

[soure,java]
----
Class<?> myClassClass = Compiler.compile("com.sb.demo.MyClass", source);

----

The method's first parameter is the binary name of the class.
The second parameter is the string source code of the class.

[NOTE]
====
The binary name of a class is the name returned by the method `Class.getName()`.
A class can have three different names:

* Simple name,

* Canonical name, and

* Binary name, many times referred to as name.

The simple name is the name of the class without any package prefix or enclosing class prefix.
The canonical name is the name we usually refer to the classes in the Java source unless imported.
The binary name is the name of how the JVM knows the class.
With some simplification, the binary name of the class has the `$` in it for anonymous and inner classes.
Canonical names have `.` between the name of the outer class and the inner classes' names.
Anonymous classes have no canonical name.
In other cases, the binary and canonical names are the same.
====

The method's return value is the class compiled and loaded into the JVM.

If there is an error during the compilation, the call will throw a `CompileException` with the error message in the exception message.

== Fluent API

The fluent API is available when there are more files to be compiled or when you want to do something other than loading with the class files.

The fluent API is chained, offering the possible methods only at the locations where you can use them.
To demonstrate the use of the API, we will use the sample code:

[source,java]
----
 1. String sourceFirstClass = "package com.sb.demo;\n" +
 2.         "\n" +
 3.         "public class FirstClass {\n" +
 4.         "    public String a() {\n" +
 5.         "        return \"x\";\n" +
 6.         "  }\n" +
 7.         "}";
 8. final var compiled = Compiler.java()
 9.         .from("com.sb.demo.FirstClass", sourceFirstClass)
10.         .from(Paths.get("src/test/java"))
11.         .compile();
12. compiled.saveTo(Paths.get("./target/generated_classes"));
13. compiled.stream().forEach(bc -> System.out.println(Compiler.getBinaryName(bc)));
14. final var loaded = compiled.load();
15. Class<?> firstClassClass = loaded.get("com.sb.demo.FirstClass");
16. loaded.stream().forEach( klass -> System.out.println(klass.getSimpleName()));
17. final var compiler = loaded.reset();
18. final var sameCompiler = compiled.reset();

----



=== 1.  Get the compiler object

To start the compilation, you must have a `Compiler` object.
To get that, you have to call the

[source,java]
----
        final var compiled = Compiler.java()

----

=== 2.  Add sources

The next step is to add the source files to the compiler object.
To do that, you can specify the sources one by one as strings, or you can add directories where the source files are.
The overloaded method `from()` is used for both operations.

To add sources individually, you can call

[source,java]
----
                .from("com.sb.demo.FirstClass", sourceFirstClass)

----

The first argument is the binary name of the class.
The second is the actual source code.
To add multiple sources, you can call this method one after the other multiple times.
However, if the sources are in the file system in a directory, you can also call

[source,java]
----
                .from(Paths.get("src/test/java"))

----

In this call, you specify only one parameter, a path pointing to the source root.
It is the directory where the directory structure matching the Java package structure starts.
You can have many calls to this method if you have multiple source trees on the disk.
You can also add some of the sources as strings, individually and others scanned from the file system.

=== 3.  Compile

After the program loaded the sources, the next thing is to compile:

[source,java]
----
                .compile();

----

The compilation generates the bytes codes for the Java source files.
They are not loaded as Java classes into the memory yet.

=== 4.  Save the byte codes

The next step you can do is save the byte codes.
It is not a must.
You can ignore this step if you do not need the compiled byte codes in the file system.

[source,java]
----
        compiled.saveTo(Paths.get("./target/generated_classes"));

----

The argument to this method is the path to where the program will save the class files.
If the directory does not exist, the code will create it recursively.
It will create all the subdirectories corresponding to the package structure.
Adding this directory to a standard URL class loader will be able to load these files from the disk.

The return value of this method is `void`, not chainable.
This method is usually the last action you invoke on a compiler.

=== 5.  Stream through the byte codes

Sometimes you do not want to save the byte code to `.class` files.
You can use the compiler object at this stage to iterate through the compiled codes, calling

[source,java]
----
        compiled.stream().forEach(bc -> System.out.println(Compiler.getBinaryName(bc)));

----

The return value of the method `stream()` at this point is `Stream<byte[]>`.
It is up to you how you use these byte arrays.

Many times you may also need the binary name of the class.
You can call the static method `getBinaryName()` to get the name.
It is a utility method that gauges the name of the class from the binary representation.
You can use this method for any byte code, not only those compiled with the compiler.

NOTE: The `getBinaryName()` implementation supports JVM byte code up to 63, which is Java 19.

The API built into the Java run-time is complex because it was designed to handle several input files (Java source code) and output files (generated byte code) reading and writing possibilities. Therefore, it needs the implementation of complex classes that provide the source code and store the generated byte code.

To ease the burden, this library implements these classes and class loaders to handle the simple case when you want to compile Java source available during run-time in String objects, and you want to load the compiled classes instead of generating `.class` files.

=== 6.  Load the classes

Applications want not only to compile the Java classes on the fly but also to load them.
The aptly named method `load()` can be used to do that.

The method `load()` has two versions.
One is without argument; the other needs a class loader.
The more straightforward and recommended way is:

[source,java]
----
        final var loaded = compiled.load();

----

It will load the classes from the memory-stored byte code to the JVM.
This loading will convert the byte codes to `Class` objects.

A version named `loadHidden()` will use a special class loader loading the class as a hidden class.
link:https://openjdk.org/jeps/371[JEP371] describes hidden classes.
They are classes dynamically loaded by the program but are hidden because they do not have a canonical name.
The only way to access them is via reflection using the class object returned by the library (see the next chapter).
Hidden classes have a technical name; hence you will get some value if you call `getName()` or `getSimpleName()` on the class.
On the other hand, `getCanonicalName()` will return `null`.
`getCanonicalName()` returns the format of the name used in the Java source code to refer to the class.

NOTE: You can load many hidden classes in the source code with the same name.
The Java run-time will delete the name.
SourceBuddy can also load several versions of a single named class, but you must use different compiler objects.
The reason: the `Compiler` object identifies the classes using the names you provided for the compilation.
If two classes have the same name, then `loaded.get(className)` would not know which version it has to return.

[NOTE]
====
This hidden class loading cannot work without a `Lookup` object.
This object is used to create the new hidden class.
The compiled class has to be in the same package as the code that creates the lookup objects.

The recommended way is

* to create a lookup object calling `MethodHandles.lookup()`

* passing the resulting object to the method `loadHidden()` as first argument, and

* have the compiled class in the same package as the code using the `Compiler`.

This may look as simple as

[source,java]
----
Compiler.java().from("Z", "class Z{}").compile().loadHidden(MethodHandles.lookup());
----

For a simpler interface you can also call the metjod without this argument, as

[source,java]
----
Compiler.java().from("Z", "class Z{}").compile().loadHidden();
----

====

[NOTE]
====
The hidden class loading can also have `ClassOption` vararg arguments.
These control whether a loaded hidden class becomes attached to the classloader and to be a member of a nest host.
To accommodate the possibility, the method `loadHidden(MethodHandles.Lookup lookup, ClassOption... options)` also accepts these as vararg parameters.
====

Note that the methods `load()` and `loadHidden()` return objects which handle the loaded classes.
These are not the compiler object.

=== 7.  Get access to the classes

When the classes are loaded, your code will want to access some of them.
Since the code creates these classes run-time, they are not available during the compile time of your program.
You can access the class objects from the compilers.
After that, you can use casting to an interface the class implements, a superclass, or a standard reflection API.

To get a class object by its name, you can call

[source,java]
----
        Class<?> firstClassClass = loaded.get("com.sb.demo.FirstClass");

----

The class also contains a complimentary method called `newInstance(String className, Class type)`.
When you call

[source,java]
----
        Object f = loaded.newInstance("com.sb.demo.FirstClass",Object.class);"
----

you will get a new instance of the class.
The second argument can be `Object.class` or any class of interface the dynamically compiled class extends or implements, and you can cast the object to this type.
This method is generic; the return type will be the given type, so casting is not necessary.


=== 8.  Stream through the class objects

You can also get a stream of the classes.

[source,java]
----
        loaded.stream().forEach( klass -> System.out.println(klass.getSimpleName()));

----

Since the method `load()` returned a new object, the method `stream()` is different this time.
It returns a `Stream<Class>` type and not the byte codes.

=== 9.  Reset the compiler

Last but not least, you can reset the compiler.
You may need to reset the compiler to reuse it to compile additional sources.
In most cases, it is better to get a new compiler calling

[source,java]
----
        final var compiled = Compiler.java()

----

The only case when the reuse of the compiler is needed is when the classes in the new compilation etap need access to the classes in the previous etap.
Using two different compiler objects will compile classes that see the classes of the 'host' code and the classes added to the compiler, but not each other.
When a compiler object is reset, the subsequent compilation round will see all the host classes and all the classes compiled previously and added in the current etap.

When the compilation starts, the compiler will compile all the java classes you ever added to the compilation.
It means that older classes will be recompiled, consuming CPU.
I recommend not resetting the compiler object except when needed.

To reset the compiler, you can invoke the method

[source,java]
----
        final var compiler = loaded.reset();

----

You can invoke this method on the compiler object, even if you used it to create a loaded object:

[source,java]
----
        final var sameCompiler = compiled.reset();

----

The object you get back from both of these calls is the same as the one you can call

[source,java]
----
        final var compiled = Compiler.java()

----

except that it already contains the classes you added to it previously.

WARNING: You can not redefine a class the program has already compiled.
The program will compile the new source file for an existing class name.
It will store the byte code; you will get the new version when calling `stream()`; you can save the new version.
However, when you call `load()`, it will not load into memory.
The class loader will see that a class under its management is already loaded and skip the loading.
It is a limitation of the Java class loading structure.
A class loader cannot unload and reload a class.

You cannot reset a compiler that you used to load hidden classes.
Hidden classes have no names.
The newly defined classes cannot reference them.
In this case, a reset compiler object would increase the CPU load without any added benefit.

== Loading Hidden Classes

This chapter describes some technical details about hidden class loading.
It gives a reason why it is recommended to pass a lookup object to the method `loadHidden()`.
Understanding the details here is not necessary to use the library.
The simple approach is the following:


. Use the `loadHidden()` method without a lookup object.
If the performance is acceptable for your application you are done.
. Use the version passing a lookup object and test your performance.
You may also modify the package of the compiled class.

And not the technical details.

When calling `loadHidden()` without a lookup object the class loader will create one.
It will be from the same package as the compiled class.
To do that, however, it performs a resource intensive task.
The `MethodHandles.lookup()` call creates a lookup object for the caller class and package.
In this case that would be the class loader class' package, which is `com.javax0.sourcebuddy`.
This is not likely to be the package your compiled source class is in.

The version of the method `lookup()` that gets the class as argument is not public.
You cannot create a lookup object for anything else than the caller.
The class loader has to have a class,

* which is in the same package as the compiled class,

* has a method that creates a lookup object and returns it to be used by the class loader.

To do that the class loader fires up a new `Compiler` object and creates a class implementing the `Supplier` interface.
Then it calls the `Supplier.get()` method to get access to the lookup object.

Since this process needs a new compiler, source compilation, creating a new class loader object and invoking the created dynamic class object it will take some time that may be significant in your case.

== Support

The project is open-source; non-commercial; the license is Apache v2.0.
A single person actively develops it at the moment.
If you see that the latest release or commit was not many years ago, then it is worth a try to ask, open a ticket, and so.
I will react and help you as much as I can afford.
