
= SourceBuddy





== Introduction
.This documentation is about the version 2.1.0-SNAPSHOT of the software.

You can compile Java source code you created dynamically in your Java application.
Your program can create the source code of one or more Java classes, pass the strings to SourceBuddy and use the classes.
An example code is the following:

[source,java]
----
String source = """
        package com.sb.demo;

        public class MyClass implements Talker {
            @Override
            public void say() {
                System.out.println("Hello, Buddy!");
          }
        }""";
Class<?> myClassClass = Compiler.compile(source);
Talker myClass = (Talker) myClassClass.getConstructor().newInstance();
myClass.say();

----

SourceBuddy is a simple Java source compiler facade in front of the JDK-provided `javac` compiler.
I designed it for applications creating Java source code on the fly during run-time.
The JDK API is complex and hard to use.
There is nothing in SourceBuddy you could not do with the JDK alone.
However, using SourceBuddy, it is much simpler.
This way, you do not need to implement anything except your application logic.

All you need follow the steps as depicted here:

image::images/compile_flow.svg[]

You

. get a `Compiler` object calling the `Compiler.java()`, and from there, all you need is
. specify the source code either as Java strings or files,
. call `compile()`,
. fetch the compiled `.class` files as `byte[]`, save to file or the load the classes, OR
. use the class and instances (not on the picture, it is already up to you).


There are two apis.

* A simple API with one call for simple cases compiling one class only, and

[source,java]
----
Compiler.compile(source).getConstructor().newInstance();
----

* a more versatile fluent API for cases being a bit more complex.

[source,java]
----
Compiler.java().from(source).compile().load().newInstance(Talker.class);
----

In this document, we will explain the details of how to use the library, including

* Maven coordinates,

* Simple API,

* Fluent API,

* Handling Hidden Classes,

* Creating and Loading Inner Classes, and

* Support.

== Maven Coordinates

The library is available from Maven central.
The Maven central coordinates are:

[source,xml]
----
<dependency>
    <groupId>com.javax0.sourcebuddy</groupId>
    <artifactId>SourceBuddy</artifactId>
    <version>2.1.0-SNAPSHOT</version>
</dependency>
----

SourceBuddy requires Java 17.

Documentation on the different link:RELEASES.adoc[releases].

== Simple API

You can use the simple API in simple projects compiling and loading one class at a time.
To do that, the class `com.javax0.sourcebuddy.Compiler` defines a static method `compile()`.
Here is the line from the example displayed in the introduction using this method:

[soure,java]
----
Class<?> myClassClass = Compiler.compile(source);

----

The method's parameter is the string source code of the class.

The method's return value is the class compiled and loaded into the JVM.

If there is an error during the compilation, the call will throw a `CompileException` with the error message in the exception message.

There are four overloaded versions of the static `compile()` method.
Using the previous source code, it can be compiled in four different ways:

[source,java]
----
 1. Class<?> objectClassImplicitName = Compiler.compile(source);
 2. Class<?> objectClass = Compiler.compile(name, source);
 3. Class<Talker> classImplicitName = Compiler.compile(source, Talker.class);
 4. Class<Talker> klass = Compiler.compile(name, source, Talker.class);

----

. Providing only the source code as we have already seen before.
. Providing the name of the class and the source code.
This version should be used, when the library cannot figure out the name of the class from the source code.
The library uses simple pattern matching to find the package and class names in the Java source.
. The same as the first version, but you can also provide a class for the loaded type.
This can be used when the class in the source code implements and interface or extends a class which is available during the compile time.
The returned class object can be cast to that type and the library will do that casting for you.
. The same as the second version, but again you can provide a class for the casting.

== Fluent API

The fluent API is available when there are more files to be compiled.

To demonstrate the use of the API, we will use the sample code:

[source,java]
----
 1. String sourceFirstClass = """
 2.         package com.sb.demo;
 3. 
 4.         public class FirstClass {
 5.             public String a() {
 6.                 return "x";
 7.           }
 8.         }""";
 9. final var compiled = Compiler.java()
10.         .from("com.sb.demo.FirstClass", sourceFirstClass)
11.         .from(Paths.get("src/test/java"))
12.         .compile();
13. compiled.saveTo(Paths.get("./target/generated_classes"));
14. compiled.stream().forEach(bc -> System.out.println(Compiler.getBinaryName(bc)));
15. final var loaded = compiled.load();
16. Class<?> firstClassClass = loaded.get("com.sb.demo.FirstClass");
17. Object firstClassInstance = loaded.newInstance("com.sb.demo.FirstClass");
18. loaded.stream().forEach(klass -> System.out.println(klass.getSimpleName()));
19. final var compiler = loaded.reset();
20. final var sameCompiler = compiled.reset();

----


In the following sections we wil go through the lines of the code explaining their meaning.



=== 1.  Get the compiler object

To start the compilation, you must have a `Compiler` object.
To get that, you have to call the


[source,java]
----
        final var compiled = Compiler.java()

----

=== 2.  Add sources

The next step is to add the source files to the compiler object.
To do that, you can specify the sources one by one as strings, or you can add directories where the source files are.
The overloaded method `from()` is used for both operations.

To add sources individually, you can call

[source,java]
----
                .from("com.sb.demo.FirstClass", sourceFirstClass)

----

The first argument is the binary name of the class.
The second is the actual source code.

You can omit the class name.
This information is already in the source code after all.
The class name is required by the JDK compiler.
SourceBuddy has to provide it.
To do that it either gets it as an argument or tries to figure out even before compiling the code.
Use the one without the name, and specify the name only in special cases when SourceBuddy cannot identify it.

To add multiple sources, you can call this method multiple times.

If the sources are in the file system in a directory, you can also call

[source,java]
----
                .from(Paths.get("src/test/java"))

----

In this call, you specify only one parameter.
A path pointing to the source root.
It is the directory where the directory structure matching the Java package structure starts.
You can have many calls to this method if you have multiple source trees on the disk.
You can also add some sources as strings, individually and others scanned from the file system.

NOTE: The class names are calculated from the directory structure and the name of the file.
The class name of a single class is calculated the same way as before when the path points to a single file.
You can also provide the class name as string and a path to a single source file.

The path can also point to an individual file.
In this case the individual file should contain the source code.
The class name will be calculated the same way as giving the source from a string.
If the name of the class cannot be specified then the name can be given as first argument before the path to the file.
In this case the path has to point to an individual file.
Pointing to a directory in this case is an error.

=== 3.  Hide the class

You can call the method `hidden()` when you want to load a class hidden.
Hidden and non-hidden classes can be mixed in one SourceBuddy compiler object.
You can either call `hidden()`, `named()`, or `nest()`.
These calls are optional, but only one of them should be called for a source.
Different versions of these methods accept arguments to specify lookup object, and class loading configuration.

Loading hidden classes is a complex topic, and it is detailed later in a separate chapter.

=== 4.  Compile

After the program loaded the sources, the next thing is to compile:

[source,java]
----
                .compile();

----

The compilation generates the bytes codes for the Java source files.
They are not loaded as Java classes into the memory yet.

=== 5.  Save the byte codes

The next step you can do is saving the byte codes.
It is not a must.
You can ignore this step if you do not need the compiled byte codes in the file system.

[source,java]
----
        compiled.saveTo(Paths.get("./target/generated_classes"));

----

The argument to this method is the path to where the program will save the class files.
If the directory does not exist, the code will create it recursively.
It will create all the subdirectories corresponding to the package structure.
Adding this directory to a standard URL class loader will be able to load these files from the disk.

The return value of this method is `void`, not chainable.
This method is usually the last action you invoke on a compiler.

=== 6.  Stream through the byte codes

Sometimes you do not want to save the byte code to `.class` files.
You can use the compiler object at this stage to iterate through the compiled codes, calling

[source,java]
----
        compiled.stream().forEach(bc -> System.out.println(Compiler.getBinaryName(bc)));

----

The return value of the method `stream()` at this point is `Stream<byte[]>`.
It is up to you how you use these byte arrays.

Many times you may also need the binary name of the class.
You can call the static method `Compiler.getBinaryName()` to get the name.
It is a utility method that gauges the name of the class from the binary representation.
You can use this method for any byte code, not only those compiled with the compiler.

NOTE: The `getBinaryName()` implementation supports JVM byte code up to 63, which is Java 19.
Note that these version values are automatically pulled from the source code using Jamal.
They are always up-to-date in this documentation.

=== 7.  Load the classes

Applications usually want to load the classes after compilation.
The aptly named method `load()` can be used to do that.

[source,java]
----
        final var loaded = compiled.load();

----

It will load the classes from the memory-stored byte code to the JVM.
This loading will convert the byte codes to `Class` objects.

The method `load()` get `Compiler.LoaderOption` arguments.
The possible values are

* `REVERSE`  will load the compiled classes first even if a class with the same name is already loaded.
         The default behaviour is to call the parent class loader first.
         Using this option reverses this strategy.
         In the case of hidden classes this is the default strategy and there is no possibility to reverse it.
* `NORMAL`  is the default.
         Consult the parent class loader first to load classes.
         The compiler's class loader is used only if the other class loaders could not load the class.


When a class was specified to be hidden calling the method `hidden()` after the `from()` method the class is loaded as hidden class.
link:https://openjdk.org/jeps/371[JEP371] describes hidden classes.
They are dynamically loaded and hidden because they do not have a canonical name.
The only way to access them is via reflection using the class object returned by the library (see the next chapter).
Hidden classes have a technical name; hence you will get some value if you call `getName()` or `getSimpleName()` on the class.
On the other hand, `getCanonicalName()` will return `null`.
`getCanonicalName()` returns the format of the name used in the Java source code to refer to the class.
Since it is `null` you cannot reference these classes.

NOTE: Even though these classes "have no name" you still have to give them some name following the `class` keyword.
This name for the Java run-time is not interesting.
You can load many hidden classes in the source code with the same name.
SourceBuddy, on the other hand, needs a distinguishing name unique inside one compiler object.
It can also load several versions of a single named hidden class, but you must use different compiler objects.
The reason: the `Compiler` object identifies the classes using the names you provided for the compilation.
If two classes have the same name, then `loaded.get(className)` would not know which version it has to return.

[NOTE]
====
The hidden class loading cannot work without a `Lookup` object.
The lookup object is used to create the new hidden class.
It is a JDK requirement that the compiled class has to be in the same package as the code that created the lookup objects.

The recommended way is

* to create a lookup object calling `MethodHandles.lookup()`

* passing the resulting object to the method `hidden()` as first argument, and

* have the compiled class in the same package as the code using the `Compiler` and calling `MethodHandles.lookup()`.

This may look as simple as

[source,java]
----
Compiler.java().from( "package com.sb.demo;class Z{}").hidden(MethodHandles.lookup()).compile().load();
----

For a simpler interface you can also call the method without this argument, as

[source,java]
----
Compiler.java().from("Z", "class Z{}").hidden().compile().load();
----

Calling the method `loadHidden()` without a lookup object is more resource intensive.
====

[NOTE]
====
The hidden class loading can also have `ClassOption` vararg arguments.
These control whether a loaded hidden class becomes attached to the classloader and to be a member of a nest host.
To accommodate the possibility, the methods `hidden(ClassOption... options)` and `hidden(MethodHandles.Lookup lookup, ClassOption... options)` also accepts these as vararg parameters.
====

Note that the method `load()` returns objects which handle the loaded classes.
These are not the compiler object.

=== 8.  Get access to the classes

When the classes are loaded, your code will want to access some of them.
Since the program creates these classes run-time, they are not available during the compile time of your program.
You cannot have the names of the classes in your source code.
You can, however, access the class objects from the compilers.
After that, you can

* use casting to an interface the class implements,
* to a superclass, or
* use the standard reflection API.

To get a class object by its name, you can call

[source,java]
----
        Class<?> firstClassClass = loaded.get("com.sb.demo.FirstClass");

----

The class also contains a complimentary method called `newInstance(String className, Class type)`.
When you call

[source,java]
----
        Object firstClassInstance = loaded.newInstance("com.sb.demo.FirstClass");

----

you will get a new instance of the class.
You can use the simple name of the class assuming that the name is unique in your compilation.
If you have two or more classes with the same name in different packages you have to use the full name.
If you only have one single class in your compilation you can omit the name and call `get()` or `newInstance()` without a name.

You can also call the method `newInstance()` specifying the class of the instance in the case the compiled class implements an interface or extends a class.
The `newInstance()` method also has a version that accepts a `Class` and an `Object` array argument to call a constructor that needs parameters.
This is unavoidable when you crate a new inner class and make it to be a nest mate of an already existing object.

=== 9.  Stream through the class objects

You can also get a stream of the classes.

[source,java]
----
        loaded.stream().forEach(klass -> System.out.println(klass.getSimpleName()));

----

Note that this is not the same `stream()` method we called after the compilation.
That method returned a stream of byte arrays.
This method returns a stream of class objects.

=== 10.  Reset the compiler

Last but not least, you can reset the compiler.
You may need to reset the compiler to reuse it to compile additional sources.
In most cases, it is better to get a new compiler calling

[source,java]
----
        final var compiled = Compiler.java()

----

The only case when the reuse of the compiler is needed when the classes in the new compilation etap need access to the classes from previous etaps.
Using two different compiler objects will compile classes that see the classes of the 'host' code and the classes added to the compiler, but not each other.
When a compiler object is reset, the subsequent compilation round will see all the host classes and all the classes compiled previously and added in the current etap.

image::images/visibility.svg[]

When the compilation starts, the compiler will compile all the java classes you ever added to the compilation.
It means that older classes will be recompiled, even though they were already compiled,consuming CPU.
I recommend not resetting the compiler object except when needed.

To reset the compiler, you can invoke the method

[source,java]
----
        final var compiler = loaded.reset();

----


You can invoke this method on the compiler object, even if you used it to create a "Loaded" object:

[source,java]
----
        final var sameCompiler = compiled.reset();

----

The object you get back from both of these calls is the same as the one you originally got calling

[source,java]
----
        final var compiled = Compiler.java()

----

except that it already contains the classes you added previously.

WARNING: You can not redefine a class the program has already compiled.
The compilation will fail the same way as if you specified two identically named classes.
You cannot have two identically named classes added to a compiler object even if hidden.

== Loading Hidden Classes

This chapter describes some technical details about hidden class loading.
In the previous chapter in section 7.  we discussed the hidden class loading.
There is a method `hidden()` to specify that the last source/class added to the compiler is hidden.
The method has a version that accepts a lookup object as argument; and we also said that using it without this argument is more resource intensive.

In this chapter we will describe why it is the case.
Understanding the details here is not necessary to use the library.

The simple approach is the following:

. Use the `hidden()` method without a lookup object.
If the performance and functionality is acceptable for your application you are done.
. Use the version passing a lookup object and test your performance.
You may also need to select compiled class' package properly.

And now, the technical details.

When calling `hidden()` without a lookup object the class loader will create one.
It will be from the same package as the compiled class.
To do that, however, it performs a resource intensive task.
The `MethodHandles.lookup()` call creates a lookup object for the caller class and package.
In this case that would be the class loader class' package, which is `com.javax0.sourcebuddy`.
It is not likely to be the package your compiled source class is in.
It is a package of SourceBuddy.

The version of the method `lookup()` that gets the class as argument is not public in the JDK.
You cannot create a lookup object for anything else than the caller.
And still, the class loader needs that for you to load your hidden class.

It has to have a class,

* which is in the same package as the compiled class,

* has a method that creates a lookup object and returns it to be used by the class loader.

The class loader fires up a new `Compiler` object and creates a class implementing the `Supplier` interface.
The implementation creates a lookup object and returns it.
The class loader code calls the `Supplier.get()` method to get access to the lookup object.
Here is the actual code that does that:

[source,java]
----
final byte[] lcByteCode = Compiler.java().from(packageDot + name, """
        %s

        import java.util.function.Supplier;
        import java.lang.invoke.MethodHandles;

        public class %s implements Supplier<MethodHandles.Lookup> {
            public %s(){}
            @Override
            public MethodHandles.Lookup get() {
                return MethodHandles.lookup();
            }
        }
        """.formatted(p.line, name, name)).compile().get();
final var supplier = defineClass(canonicalName, lcByteCode, 0, lcByteCode.length);
final var lookup = (MethodHandles.Lookup) ((Supplier<?>) supplier.getConstructor().newInstance()).get();

----

[NOTE]
====
In the code above the variable `p.line` contains the keyword `package`, the name of the package and a `;` semicolon at the end.
When the generated class is in the default package this variable is empty.

`name` is the simple name, `canonicalName` is the canonical name of the class.
The class name is a random unique string (random uuid).

====

Since this process needs a new compiler, source compilation, creating a new class loader object and invoking the created dynamic class object it will take some time that may be significant in some cases.

== Loading Inner Class(es)

To load and add a new inner class to an existing class you need to have the byte code of the inner class.
Since the outer class in this use case already exists and Java does not provide a syntax to specify an inner class outside the embedding class we have to apply a little trick.

The source code containing the inner class should partially contain the embedding class.
It does not need to have all the code though.
It has to have the fields and the methods that the inner class uses.
The type of the fields and the signature of the methods have to match.
The content of the methods in the outer class is not important.
You can usually just leave that empty.
The inner class or classes inside the outer class should have their Java code.
After the source code was added to the compiler calling one of the `from()` methods you have to call `nest()`.

Calling `nest()` will inform SourceBuddy that the outer class inside the source is a nesting host.
The inner classes will be loaded automatically as hidden classes.
The outer class compiled will not be loaded.

The tests of the application contain a demo class:

[source,java]
----
package com.javax0.sourcebuddytest;

import com.javax0.sourcebuddy.DynExt;

import java.lang.invoke.MethodHandles;

public class OuterClass implements DynExt {

    private int z = 55;

    public int getZ() {
        return z;
    }

    public MethodHandles.Lookup getLookup(){
        return MethodHandles.lookup();
    }
}

----

The test code that creates a new inner class to the already existing outer class is the following:

[source,java]
----
final var outer = new OuterClass();
final var lookup = outer.getLookup();
final var inner = Compiler.java().from("""
                package com.javax0.sourcebuddytest;

                public class OuterClass {
                    private int z=33;

                    public class Inner {
                       public void a(){
                         z++;
                       }
                    }

                }""").nest(lookup, MethodHandles.Lookup.ClassOption.NESTMATE).compile().load()
        .newInstance("Inner", classes(OuterClass.class), args(outer));
final var m = inner.getClass().getDeclaredMethod("a");
m.invoke(inner);
Assertions.assertEquals(56, outer.getZ());

----

[NOTE]
====
To create and load an inner class to an already existing class you need a lookup object from the already existing class.
To do that the class implements the `DynExt` interface.
The method `getLookup()` will provide a lookup object from the same package, from the same module.
It makes it possible to get an inner class that can be the nest mate of the already existing class.
====

== Support

link:https://github.com/sourcebuddy/sourcebuddy/issues/[GitHub Issues]
...
link:https://github.com/sourcebuddy/sourcebuddy/issues/new[Create New Issue]
...
link:https://github.com/sourcebuddy/sourcebuddy/pulls[Pull Requests]
...
link:https://github.com/sourcebuddy/sourcebuddy/fork[Create a Fork]

The project is open-source; non-commercial; the license is Apache v2.0.
A single person actively develops it at the moment.
If you see that the latest release or commit was not many years ago, then it is worth a try to ask, link:https://github.com/sourcebuddy/sourcebuddy/issues/new[open a ticket].
I will react and help you as much as I can afford.

You are welcome to open tickets in GitHub if you have any question, but also for suggestions and only if you like the tool.
Usually I struggle with lacking the information about how many are using my tools.
Do not leave me in the dark.
