
== SourceBuddy Release history


=== link:https://github.com/sourcebuddy/sourcebuddy/tree/2.2.0[2.2.0]

You can add modules to the compilation unit using the `modules()` method.
Class and module path are added automatically to the compiler options unless you call `isolate()`.

=== link:https://github.com/sourcebuddy/sourcebuddy/tree/2.1.0[2.1.0]

The individual classes can be each hidden or named (not hidden).
Named classes can also be loaded using lookup object.
Class can be denoted as nesting class mimicking already existing class.

=== link:https://github.com/sourcebuddy/sourcebuddy/tree/2.0.0[2.0.0]

Major restructuring of the class loading structure.
With this release hidden and non-hidden classes can be mixed.
There is no more `loadHidden()` method supported.
Instead, you can call `hidden()` for each added source separately.

Since this change, removing a method from the API? is not backward compatible, this is a new major version.

=== link:https://github.com/sourcebuddy/sourcebuddy/tree/1.1.1[1.1.1]

Fix to cache some resources.
Prior version had a bug not storing created methods handles in the cache.

=== link:https://github.com/sourcebuddy/sourcebuddy/tree/1.1.0[1.1.0]

Fix to work with hidden classes properly and also adds extra APU.

=== link:https://github.com/sourcebuddy/sourcebuddy/tree/1.0.0[1.0.0]

Initial release.
Support hidden classes, but it does not work due to a bug.
